[package]
name = "smolmask"
version = "0.1.1"
edition = "2021"
description = "A small library for storing small binary masks in just a single integer."
license = "MIT"

[dependencies]
num = "0.4.1"
num-traits = "0.2.15"
